server:
  port: 8080

spring:
  application:
    name: myproject
  # 开启懒加载
#  main:
#    lazy-initialization: true
  # 不使用 devtools 设置的一些默认皮遏制，如缓存关闭等
#  devtools:
#    add-properties: false
#    restart: # 每次重启日志记录变化的报告，默认是 true
#      log-condition-evaluation-delta: false
      # 自定义哪些位置的文件变动不会引起重启
#      exclude: static/**, public/**
      # 保持默认的排除位置基础上添加排除
  # 关闭程序启动的日志
#  banner:
#    location: META-INF/banner/banner.txt
#  main:
#    log-startup-info: false
#      additional-exclude: static/**


