server:
  port: 8080

# 自定义属性::
name: zhangsan

acme:
  remote-address: 192.168.1.1 # 支持 remote-address 匹配 remoteAddress
  security:
    username: admin
    roles:
      - USER
      - ADMIN
  list:
    - name: my name
      description: my description
  map:
    key1:
      name: my name 1
      description: my description 1

--- # 只能是三个线，不能多
spring:
  profiles: dev
#  application:
#    name: myproject
acme:
  list:
    - name: my another name
  map:
    key1:
      name: dev name 1
    key2:
      name: dev name 2
      description: dev description 2

#spring:
#  application:
#    name: myproject
  # 开启懒加载
#  main:
#    lazy-initialization: true
  # 不使用 devtools 设置的一些默认皮遏制，如缓存关闭等
#  devtools:
#    add-properties: false
#    restart: # 每次重启日志记录变化的报告，默认是 true
#      log-condition-evaluation-delta: false
      # 自定义哪些位置的文件变动不会引起重启
#      exclude: static/**, public/**
      # 保持默认的排除位置基础上添加排除
  # 关闭程序启动的日志
#  banner:
#    location: META-INF/banner/banner.txt
#  main:
#    log-startup-info: false
#      additional-exclude: static/**

# 随机值
my:
  rval: ${random.value}
  rint: ${random.int}
  rlong: ${random.long}
  ruuid: ${random.uuid}
  rlessten: ${random.int(10)}
  rrange: ${random.long()}
#  rrange: ${random.int[1024, 65536]}
  servers:
    - dev.example.com
    - another.example.com

# 占位符
app:
  name: MyApp
  description: ${app.name} is a Spring Boot Application

